[workspace]
members = ["core", "backends-age", "backends-7z", "cli", "integration-tests"]
resolver = "2"

[workspace.package]
version = "0.3.2"
authors = ["msoleimani62 <msoleimaniphone@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/msoleimani62/ramz"
rust-version = "1.75"

[workspace.dependencies]
ramz-core = { path = "core", version = "0.3.2" }
ramz-backends-age = { path = "backends-age", version = "0.3.2" }
ramz-backend-7z = { path = "backends-7z", version = "0.3.2" }
ramz-cli = { path = "cli", version = "0.3.2" }

thiserror = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
rpassword = "7"
tempfile = "3"
walkdir = "2"
tar = "0.4"
zstd = "0.13"
age = { version = "0.10", features = ["armor"] }
chacha20poly1305 = "0.10"
argon2 = { version = "0.5", features = ["password-hash"] }
rand = "0.8"
zeroize = { version = "1", features = ["zeroize_derive"] }
regex = "1"
which = "6"
dirs = "5"
sha2 = "0.10"
ml-kem = { version = "0.3", features = ["getrandom"] }
