use std::fs;
use std::path::PathBuf;

use crate::{PackOptions, RamzError, Result, SourceKind, Target};

// Report generated by dry-run estimation
// گزارش تولید شده توسط تخمین dry-run
#[derive(Debug)]
pub struct DryRunReport {
    pub source_path: PathBuf,
    pub source_kind: SourceKind,
    pub source_size: u64,
    pub estimated_archive_size: u64,
    pub compression_ratio: f64,
    pub output_path: PathBuf,
    pub backend_name: &'static str,
    pub password_protected: bool,
    pub will_delete_source: bool,
    pub will_secure_delete: bool,
    pub already_compressed_files: Vec<PathBuf>,
    pub compressible_files: Vec<PathBuf>,
}

// Format byte size to human-readable string
// تبدیل حجم بایت به رشته قابل خواندن
pub fn format_size(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KB", "MB", "GB", "TB"];
    if bytes == 0 {
        return "0 B".to_string();
    }
    let exp = (bytes as f64).log(1024.0).min(UNITS.len() as f64 - 1.0) as usize;
    let value = bytes as f64 / 1024f64.powi(exp as i32);
    format!("{:.1} {}", value, UNITS[exp])
}

// Estimate archive size without creating it
// تخمین حجم آرشیو بدون ساختن آن
pub fn estimate_archive_size(
    target: &Target,
    opts: &PackOptions,
    backend_name: &'static str,
) -> Result<DryRunReport> {
    let mut already_compressed = Vec::new();
    let mut compressible = Vec::new();

    match target.kind {
        SourceKind::File => {
            if super::compression::is_already_compressed(&target.path) {
                already_compressed.push(target.path.clone());
            } else {
                compressible.push(target.path.clone());
            }
        }
        SourceKind::Directory => {
            for entry in walkdir::WalkDir::new(&target.path) {
                let entry = entry.map_err(|e| RamzError::Backend(e.to_string()))?;
                if entry.file_type().is_file() {
                    let path = entry.path().to_path_buf();
                    if super::compression::is_already_compressed(&path) {
                        already_compressed.push(path);
                    } else {
                        compressible.push(path);
                    }
                }
            }
        }
    }

    // Rough estimation: compressible files ~30% of original, already compressed ~100%
    // تخمین تقریبی: فایل‌های قابل فشرده‌سازی ~30٪ از اصلی، فایل‌های فشرده‌شده ~100٪
    let mut estimated = 0u64;
    for path in &compressible {
        if let Ok(meta) = fs::metadata(path) {
            estimated += meta.len().max(1) / 3;
        }
    }
    for path in &already_compressed {
        if let Ok(meta) = fs::metadata(path) {
            estimated += meta.len();
        }
    }

    // Add tar header overhead (~512 bytes per entry)
    // اضافه کردن سربار هدر tar (~512 بایت برای هر entry)
    estimated += ((compressible.len() + already_compressed.len()) as u64) * 512;

    // Add encryption overhead (~1KB for age headers)
    // اضافه کردن سربار رمزنگاری (~1KB برای هدرهای age)
    estimated += 1024;

    let ratio = if target.total_bytes > 0 {
        estimated as f64 / target.total_bytes as f64
    } else {
        1.0
    };

    let output_path = opts
        .output_dir
        .as_ref()
        .map(|d| {
            d.join(format!(
                "{}.{}",
                target
                    .path
                    .file_stem()
                    .unwrap_or_default()
                    .to_string_lossy(),
                if backend_name == "age" {
                    "age.tar.zst"
                } else {
                    "7z"
                }
            ))
        })
        .unwrap_or_else(|| {
            PathBuf::from(format!(
                "{}.{}",
                target
                    .path
                    .file_stem()
                    .unwrap_or_default()
                    .to_string_lossy(),
                if backend_name == "age" {
                    "age.tar.zst"
                } else {
                    "7z"
                }
            ))
        });

    Ok(DryRunReport {
        source_path: target.path.clone(),
        source_kind: target.kind,
        source_size: target.total_bytes,
        estimated_archive_size: estimated,
        compression_ratio: ratio,
        output_path,
        backend_name,
        password_protected: opts.password.is_some(),
        will_delete_source: opts.delete_source,
        will_secure_delete: opts.secure_delete,
        already_compressed_files: already_compressed,
        compressible_files: compressible,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Target;
    use tempfile::TempDir;

    #[test]
    fn test_format_size() {
        assert_eq!(format_size(0), "0 B");
        assert_eq!(format_size(512), "512.0 B");
        assert_eq!(format_size(1536), "1.5 KB");
    }

    #[test]
    fn test_estimate_archive_size_file() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("test.txt");
        fs::File::create(&file).unwrap();
        let target = Target::detect(&file).unwrap();
        let opts = PackOptions::default();
        let report = estimate_archive_size(&target, &opts, "age").unwrap();
        assert_eq!(report.source_size, 0);
        assert!(report.estimated_archive_size > 0);
    }
}
