[package]
name = "ramz"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ramz"
path = "src/main.rs"

[dependencies]
ramz-core = { path = "../core" }
ramz-backend-age = { path = "../backends-age" }
ramz-backend-7z = { path = "../backends-7z" }
anyhow.workspace = true
indicatif.workspace = true
clap = { version = "4", features = ["derive"] }
rpassword = "7"
