[package]
name = "ramz-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }
walkdir = { workspace = true }
tar = { workspace = true }
zstd = { workspace = true }
tempfile = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
