[package]
name = "ramz-integration-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies]
ramz-core = { workspace = true }
ramz-backends-age = { workspace = true }
ramz-backend-7z = { workspace = true }
tempfile = { workspace = true }
